//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DM.Database
{
	/// <summary>
	/// Database       : DietManager
	/// Data Source    : tcp://localhost:5432
	/// Server Version : 10.4
	/// </summary>
	public partial class DietManagerDB : LinqToDB.Data.DataConnection
	{
		public ITable<Image> Images { get { return this.GetTable<Image>(); } }
		public ITable<User>  Users  { get { return this.GetTable<User>(); } }

		public DietManagerDB()
		{
			InitDataContext();
		}

		public DietManagerDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table(Schema="Images", Name="Image")]
	public partial class Image
	{
		[PrimaryKey, NotNull] public Guid   ImageId { get; set; } // uuid
		[Column,     NotNull] public string Path    { get; set; } // text
	}

	[Table(Schema="Users", Name="User")]
	public partial class User
	{
		[PrimaryKey, NotNull] public Guid   UserId   { get; set; } // uuid
		[Column,     NotNull] public string Email    { get; set; } // character varying(60)
		[Column,     NotNull] public string UserName { get; set; } // character varying(60)
		[Column,     NotNull] public string Password { get; set; } // text
	}

	public static partial class TableExtensions
	{
		public static Image Find(this ITable<Image> table, Guid ImageId)
		{
			return table.FirstOrDefault(t =>
				t.ImageId == ImageId);
		}

		public static User Find(this ITable<User> table, Guid UserId)
		{
			return table.FirstOrDefault(t =>
				t.UserId == UserId);
		}
	}
}
